makeHeader <- function(author = "Mickael Canouil", title = "Rapport d\'Analyse", email = "mickael.canouil@good.ibl.fr", grade = "Ingenieur d\'Etudes",  documentClass = "article"){
    code <- paste("\\documentclass[12pt, a4paper]{", documentClass, "}", "\n", sep = "")
    code <- paste(code, "\\usepackage[T1]{fontenc}", "\n", sep = "")
    code <- paste(code, "\\usepackage[utf8]{inputenc}", "\n", sep = "")
    code <- paste(code, "\\usepackage[english, french]{babel}", "\n", sep = "")
    code <- paste(code, "\\usepackage{tabularx}", "\n", sep = "")
    code <- paste(code, "\\usepackage{graphicx}", "\n", sep = "")
    code <- paste(code, "\\usepackage{geometry}", "\n", sep = "")
    code <- paste(code, "\\geometry{hmargin = 2.5cm, vmargin = 2.5cm}", "\n", sep = "")
    code <- paste(code, "\\usepackage{fancyhdr}", "\n", sep = "")
    code <- paste(code, "\\pagestyle{fancy}", "\n", sep = "")
    code <- paste(code, "\\renewcommand{\baselinestretch}{1.5}", "\n", sep = "")
    code <- paste(code, "\\setlength{\\headheight}{15pt}", "\n", sep = "")
    code <- paste(code, "\\setlength{\\tabcolsep}{0.185cm}", "\n", sep = "")
    code <- paste(code, "\\makeatletter", "\n", sep = "")
    code <- paste(code, "    \\def\\maketitle{", "\n", sep = "")
    code <- paste(code, "        \\begin{titlepage}", "\n", sep = "")
    code <- paste(code, "            \\begin{center}", "\n", sep = "")
    code <- paste(code, "                {\\setlength{\\baselineskip}{0.5\\baselineskip}", "\n", sep = "")
    code <- paste(code, "                    {\\Large{\\@institute}\\linebreak}", "\n", sep = "")
    code <- paste(code, "                \\par}", "\n", sep = "")
    code <- paste(code, "                    \\vskip 0cm", "\n", sep = "")
    code <- paste(code, "                {\\setlength{\\baselineskip}{0.5\\baselineskip}", "\n", sep = "")
    code <- paste(code, "                    {\\small{\\@address}\\linebreak}", "\n", sep = "")
    code <- paste(code, "                \\par}", "\n", sep = "")
    code <- paste(code, "                    \\vfill", "\n", sep = "")
    code <- paste(code, "                {\\Huge{\\bf\\@title}}", "\n", sep = "")
    code <- paste(code, "                    \\vskip 1cm", "\n", sep = "")
    code <- paste(code, "                {par}", "\n", sep = "")
    code <- paste(code, "                    \\vskip 1cm", "\n", sep = "")
    code <- paste(code, "                {\\Large{\\@author}}", "\n", sep = "")
    code <- paste(code, "                    \\vskip 0.5cm", "\n", sep = "")
    code <- paste(code, "                {\\setlength{\\baselineskip}{0.5\\baselineskip}", "\n", sep = "")
    code <- paste(code, "                    {\\small{\\@grade}}", "\n", sep = "")
    code <- paste(code, "                \\par}", "\n", sep = "")
    code <- paste(code, "                    \\vskip 0cm", "\n", sep = "")
    code <- paste(code, "                {\\setlength{\\baselineskip}{0.5\\baselineskip}", "\n", sep = "")
    code <- paste(code, "                    {\\footnotesize{(\\@email)}}", "\n", sep = "")
    code <- paste(code, "                \\par}", "\n", sep = "")
    code <- paste(code, "                    \\vfill", "\n", sep = "")
    code <- paste(code, "                {\\large{\\@date}}", "\n", sep = "")
    code <- paste(code, "                    \\vskip 0cm", "\n", sep = "")
    code <- paste(code, "                    %\\vfill", "\n", sep = "")
    code <- paste(code, "                {\\includegraphics[height = 50pt]{figs/logo_cnrs.pdf} \\hfill \\includegraphics[height = 50pt]{figs/logo_ibl.pdf}}", "\n", sep = "")
    code <- paste(code, "                    %\\vskip 0cm", "\n", sep = "")
    code <- paste(code, "                    %{\\footnotesize{\\copyright\\@author, 2012}}", "\n", sep = "")
    code <- paste(code, "            \\end{center}", "\n", sep = "")
    code <- paste(code, "        \\end{titlepage}", "\n", sep = "")
    code <- paste(code, "    }", "\n", sep = "")
    code <- paste(code, "    \\def\\email#1{\\def\\@email{#1}}", "\n", sep = "")
    code <- paste(code, "    \\def\\institute#1{\\def\\@institute{#1}}", "\n", sep = "")
    code <- paste(code, "    \\def\\address#1{\\def\\@address{#1}}", "\n", sep = "")
    code <- paste(code, "    \\def\\grade#1{\\def\\@grade{#1}}", "\n", sep = "")
    code <- paste(code, "\\makeatother", "\n", sep = "")

    code <- paste(code, "\\title{", title, "}", "\n", sep = "")
    code <- paste(code, "\\date{\\today}", "\n", sep = "")
    code <- paste(code, "\\email{", email, "}", "\n", sep = "")
    code <- paste(code, "\\author{", author, "}", "\n", sep = "")
    code <- paste(code, "\\grade{", grade, "}", "\n", sep = "")
    code <- paste(code, "\\institute{Genomique et maladies metaboliques - UMR CNRS 8199\\linebreak", "\n", sep = "")
    code <- paste(code, "            Institut de Biologie de Lille}", "\n", sep = "")
    code <- paste(code, "\\address{E.G.I.D - FR3508 European Genomics Institute of Diabetes\\linebreak", "\n", sep = "")
    code <- paste(code, "        1 Rue du professeur Calmette\\linebreak", "\n", sep = "")
    code <- paste(code, "        59019 Lille Cedex}", "\n", sep = "")

    return(code)
}
